$axure.loadCurrentPage({
  "url":"search1_1___.html",
  "generationDate":new Date(1500857902837.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9864f7a9b4844b1da049ec432c099329",
    "type":"Axure:Page",
    "name":"search1_1_古籍",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1ba03a355af246859c9ca9fee845d618",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1300,
              "height":1348}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"116bf14fd60242d89ba9c2c35808b91e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1300,
                  "height":1348}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u0.png"}},
{
          "id":"372645fe44c84101b16481fe058d7f92",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":532,
              "y":18},
            "size":{
              "width":253,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39abe04da34a40fca60996b2712e7188",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":532,
                  "y":18},
                "size":{
                  "width":253,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eab4d11f7a264807850b9361528e1c8e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":1100,
              "height":890}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"caac3b4b043743fdb9cd23d2f2e46423",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":1100,
                  "height":890}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u4.png"}},
{
          "id":"d58031da0500457a87680e4bb5288627",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":210},
            "size":{
              "width":10,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u6_line.png"}},
{
          "id":"bfd074877dd54aad8ed861a2d23d0989",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":248},
            "size":{
              "width":50,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75e5d61aff2e41bcbbccb828cdf858d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":248},
                "size":{
                  "width":50,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u7.png"}},
{
          "id":"2e065af14b154b99963cff78f9ebabdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":326},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15f84dc6e24438a9a4ef7e87438a30c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":326},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd13b9955f374d3b84f2206c6ac01fed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":405},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b6273ba4d54a0cbc3d8324f02e7344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":405},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b93a9d96db1e4454870c9e68adc03502",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":442},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4784e3810e4846e48a7790361e9eede7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":442},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52552ab519b741069fd3a5de099e2c91",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":479},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ff2011348bc4fdaa427ab3e5bf1bbc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":479},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bdfc28443da44d7997b4e573c0c986e",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":439},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f429c6f30a334c04b4a8cf55be79ef67",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":475},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"3974123b04fe4033a0b4257c42aced4d",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":401},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"bf5ad1822f024b64ba6ce4cf492873e2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":248},
            "size":{
              "width":744,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u20_line.png"}},
{
          "id":"446b43dba70a4adc8c25860342a2f960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":998,
              "y":226},
            "size":{
              "width":152,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9b2041b2e5d4dfd9a05b68ca1a1097f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":998,
                  "y":226},
                "size":{
                  "width":152,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"596ff3aa1357432baf2c919062d101eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":482,
              "y":268},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c428e4ad27e9458f803c6c645f4b3558",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":482,
                  "y":268},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dfeb65e24ec246fda9b40bfec5c0bab7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":494,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a71fd098de2443b39811bd9203fb439b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":494,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u25.png"}},
{
          "id":"6430f85a34de466aa38489c851fd7ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":579,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6e38589fe144f3b8cbb10703833a8d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":579,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"照片list",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"72fedd1ff321497c9c5d9e48da741c69",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":664,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84f5c94bdec64e36b2269c97025f946a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":664,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"b85a9727a33942219c977e837f8dfc24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":749,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa318af98a624a6aad63a18d0f56512c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":749,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"视频list",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"25ab07eaf2a44bdf89881950b6490180",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":834,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b887c76659e42bcb6f09724b17a29e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":834,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_5全景",
                      "target":{
                        "targetType":"page",
                        "url":"search1_5__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"89bccb4aa515478e92a55ab3a355a5a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":925,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6eddd30ba594d4bbbeaa216024fefa0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":925,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_5全景",
                      "target":{
                        "targetType":"page",
                        "url":"search1_5__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"bad8bae358d44866a029d439065121aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":494,
              "y":330},
            "size":{
              "width":692,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa4c90fd89f94e7fb420efa40a50e5a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":494,
                  "y":330},
                "size":{
                  "width":692,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u37.png"}},
{
          "id":"b875a95facd946efbf3fc03d4c297cf1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":521,
              "y":503},
            "size":{
              "width":111,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e055ade767874664bcf9931884fa7f46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":521,
                  "y":503},
                "size":{
                  "width":111,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u39.png"}},
{
          "id":"7da4f45398be4a0e98ab777a8440b239",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":510},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad555a046f9044769085cf642152f9ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":510},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"806a3324a1024b6a89858f447a298a0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":661,
              "y":539},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f58f4dc484194a919ddf589e8034a9b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":661,
                  "y":539},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5593a62f355417ea67921ac980f8471",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":835,
              "y":539},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc8c0b9a49f4a058903688400694d85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":835,
                  "y":539},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"067d54465d2f46ef816d4e5e158d2ae6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":565},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71f9afb453d04eefae6acbf9d81737bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":565},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"373f407cc87843818be3f259732dc869",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":591},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e5a14c38f1a4469a27362c168f8a940",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":591},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4b686b07e4c747daa9c4792159240b75",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":476},
            "size":{
              "width":692,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u51_line.png"}},
{
          "id":"b3c39e7d1c55462787dfd4a19aeec396",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":521,
              "y":353},
            "size":{
              "width":111,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66c2519f1b8c4c37a824601b584fd15b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":521,
                  "y":353},
                "size":{
                  "width":111,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"古籍content",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 content_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"content___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u39.png"}},
{
          "id":"b969880bd858401ba24e08ce26e924a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":360},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"325abfd7b32b496bb68122c60b7601a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":360},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 content_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"content___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"984d3418494948ec9ef0a774357451a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":661,
              "y":389},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97dd93a8ec2f4f458077fda489a67b91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":661,
                  "y":389},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"901b849dcb064b32ab6f182879e1ca5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":835,
              "y":389},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59613c6516e844f18586fc434811eff1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":835,
                  "y":389},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92a8e1a84fd94271a1e934e23957b100",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":415},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"504b9e3378e14d3b99327e445694529b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":415},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a041e7740c5e4d65b44a8c5b7713964f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":441},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30c38004c4c9421ea207ad7c6b1b344c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":441},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0545b35c30b480ba7e230a3cc837834",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":521,
              "y":683},
            "size":{
              "width":111,
              "height":107}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"831c714500c34d8aa9bd28d0c1fa7fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":521,
                  "y":683},
                "size":{
                  "width":111,
                  "height":107}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u39.png"}},
{
          "id":"7bbb4bb4f7384551bbde5dced3984dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":660,
              "y":680},
            "size":{
              "width":33,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71fe02bc78d647679ceb3cc29020d8e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":660,
                  "y":680},
                "size":{
                  "width":33,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79fde58ab13a4cebbcd23869f9f52f3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":661,
              "y":709},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"777fc10418e643b3b76d2afae697b455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":661,
                  "y":709},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd5e9c661d0c40019e99c8f0097d27c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":835,
              "y":709},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4876e9977c984673a285d1ccae7d80a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":835,
                  "y":709},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86e339202a2047558340c9676aeac72a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":735},
            "size":{
              "width":61,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7d788663b54721b38eddb4b5c4cd94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":735},
                "size":{
                  "width":61,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ac62b2869b44ba784864ee1c1fdd9d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":660,
              "y":761},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c6348d04224970ad82f6fa5a630bed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":660,
                  "y":761},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"416a00e442744f1db4a4a90801bd4ea8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":494,
              "y":640},
            "size":{
              "width":692,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u51_line.png"}},
{
          "id":"0a0c30c582eb4abfbb3ad4dcc7f4dd4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":709,
              "y":881},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95fcd1c1fdbb4da8b1259fa16fa26279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":709,
                  "y":881},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u77.png"}},
{
          "id":"ce6f984ec84e46b781d2a6cda792beea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":893},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27f3f86b28524153aa21175b2200980b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":893},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6e034d48b9264374b38057333a48d08d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF003399},
            "location":{
              "x":0,
              "y":1228},
            "size":{
              "width":1300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32998be260a24529ab73d268161d7ee8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003399},
                "location":{
                  "x":0,
                  "y":1228},
                "size":{
                  "width":1300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u119.png"}},
{
          "id":"b8be1425de2b47af8d07f222055ac63c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":606,
              "y":1280},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14267f6e8a9b4c989154735a328d77f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":1280},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1db47e63419d46098a79c0efb4295d6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":123,
              "y":370},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7bece39d515a45bea8fde4db2f7f6246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":123,
                  "y":370},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b76f5cf3d6c4e03b4312d8447911c73",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":366},
            "size":{
              "width":158,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"00b6c1a880354283ac9986880256fac4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search2_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search2_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"cfef5772b96c446b890ab9ce6e18652a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":378,
              "y":84},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436dde0a07014dcf94f8d507ef90c153",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":378,
                  "y":84},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a6413371ac0f4d7a96d949281d8f9ed7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":463,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bdf3f29980b4deda21eec0b42d89bb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":463,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"44663ecea4774eb599e50e7078b6b30c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":569,
              "y":83},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71027fb027554afdb567dc36a443a4e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":569,
                  "y":83},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3552ad9e728b4944bfbdee0b1f8899f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":674,
              "y":84},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49023262c7f446588c4faffcd5b7bb66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":674,
                  "y":84},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a875eaf64bb64bbe981e2043174baa61",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":835,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7d2a29af9e2435ba2b974960096b474",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":835,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1ba03a355af246859c9ca9fee845d618":{
      "scriptId":"u0"},
    "116bf14fd60242d89ba9c2c35808b91e":{
      "scriptId":"u1"},
    "372645fe44c84101b16481fe058d7f92":{
      "scriptId":"u2"},
    "39abe04da34a40fca60996b2712e7188":{
      "scriptId":"u3"},
    "eab4d11f7a264807850b9361528e1c8e":{
      "scriptId":"u4"},
    "caac3b4b043743fdb9cd23d2f2e46423":{
      "scriptId":"u5"},
    "d58031da0500457a87680e4bb5288627":{
      "scriptId":"u6"},
    "bfd074877dd54aad8ed861a2d23d0989":{
      "scriptId":"u7"},
    "75e5d61aff2e41bcbbccb828cdf858d3":{
      "scriptId":"u8"},
    "2e065af14b154b99963cff78f9ebabdf":{
      "scriptId":"u9"},
    "e15f84dc6e24438a9a4ef7e87438a30c":{
      "scriptId":"u10"},
    "fd13b9955f374d3b84f2206c6ac01fed":{
      "scriptId":"u11"},
    "66b6273ba4d54a0cbc3d8324f02e7344":{
      "scriptId":"u12"},
    "b93a9d96db1e4454870c9e68adc03502":{
      "scriptId":"u13"},
    "4784e3810e4846e48a7790361e9eede7":{
      "scriptId":"u14"},
    "52552ab519b741069fd3a5de099e2c91":{
      "scriptId":"u15"},
    "3ff2011348bc4fdaa427ab3e5bf1bbc0":{
      "scriptId":"u16"},
    "1bdfc28443da44d7997b4e573c0c986e":{
      "scriptId":"u17"},
    "f429c6f30a334c04b4a8cf55be79ef67":{
      "scriptId":"u18"},
    "3974123b04fe4033a0b4257c42aced4d":{
      "scriptId":"u19"},
    "bf5ad1822f024b64ba6ce4cf492873e2":{
      "scriptId":"u20"},
    "446b43dba70a4adc8c25860342a2f960":{
      "scriptId":"u21"},
    "f9b2041b2e5d4dfd9a05b68ca1a1097f":{
      "scriptId":"u22"},
    "596ff3aa1357432baf2c919062d101eb":{
      "scriptId":"u23"},
    "c428e4ad27e9458f803c6c645f4b3558":{
      "scriptId":"u24"},
    "dfeb65e24ec246fda9b40bfec5c0bab7":{
      "scriptId":"u25"},
    "a71fd098de2443b39811bd9203fb439b":{
      "scriptId":"u26"},
    "6430f85a34de466aa38489c851fd7ff8":{
      "scriptId":"u27"},
    "f6e38589fe144f3b8cbb10703833a8d8":{
      "scriptId":"u28"},
    "72fedd1ff321497c9c5d9e48da741c69":{
      "scriptId":"u29"},
    "84f5c94bdec64e36b2269c97025f946a":{
      "scriptId":"u30"},
    "b85a9727a33942219c977e837f8dfc24":{
      "scriptId":"u31"},
    "fa318af98a624a6aad63a18d0f56512c":{
      "scriptId":"u32"},
    "25ab07eaf2a44bdf89881950b6490180":{
      "scriptId":"u33"},
    "1b887c76659e42bcb6f09724b17a29e2":{
      "scriptId":"u34"},
    "89bccb4aa515478e92a55ab3a355a5a5":{
      "scriptId":"u35"},
    "c6eddd30ba594d4bbbeaa216024fefa0":{
      "scriptId":"u36"},
    "bad8bae358d44866a029d439065121aa":{
      "scriptId":"u37"},
    "fa4c90fd89f94e7fb420efa40a50e5a6":{
      "scriptId":"u38"},
    "b875a95facd946efbf3fc03d4c297cf1":{
      "scriptId":"u39"},
    "e055ade767874664bcf9931884fa7f46":{
      "scriptId":"u40"},
    "7da4f45398be4a0e98ab777a8440b239":{
      "scriptId":"u41"},
    "ad555a046f9044769085cf642152f9ab":{
      "scriptId":"u42"},
    "806a3324a1024b6a89858f447a298a0a":{
      "scriptId":"u43"},
    "f58f4dc484194a919ddf589e8034a9b8":{
      "scriptId":"u44"},
    "e5593a62f355417ea67921ac980f8471":{
      "scriptId":"u45"},
    "7cc8c0b9a49f4a058903688400694d85":{
      "scriptId":"u46"},
    "067d54465d2f46ef816d4e5e158d2ae6":{
      "scriptId":"u47"},
    "71f9afb453d04eefae6acbf9d81737bc":{
      "scriptId":"u48"},
    "373f407cc87843818be3f259732dc869":{
      "scriptId":"u49"},
    "9e5a14c38f1a4469a27362c168f8a940":{
      "scriptId":"u50"},
    "4b686b07e4c747daa9c4792159240b75":{
      "scriptId":"u51"},
    "b3c39e7d1c55462787dfd4a19aeec396":{
      "scriptId":"u52"},
    "66c2519f1b8c4c37a824601b584fd15b":{
      "scriptId":"u53"},
    "b969880bd858401ba24e08ce26e924a4":{
      "scriptId":"u54"},
    "325abfd7b32b496bb68122c60b7601a6":{
      "scriptId":"u55"},
    "984d3418494948ec9ef0a774357451a6":{
      "scriptId":"u56"},
    "97dd93a8ec2f4f458077fda489a67b91":{
      "scriptId":"u57"},
    "901b849dcb064b32ab6f182879e1ca5d":{
      "scriptId":"u58"},
    "59613c6516e844f18586fc434811eff1":{
      "scriptId":"u59"},
    "92a8e1a84fd94271a1e934e23957b100":{
      "scriptId":"u60"},
    "504b9e3378e14d3b99327e445694529b":{
      "scriptId":"u61"},
    "a041e7740c5e4d65b44a8c5b7713964f":{
      "scriptId":"u62"},
    "30c38004c4c9421ea207ad7c6b1b344c":{
      "scriptId":"u63"},
    "a0545b35c30b480ba7e230a3cc837834":{
      "scriptId":"u64"},
    "831c714500c34d8aa9bd28d0c1fa7fe9":{
      "scriptId":"u65"},
    "7bbb4bb4f7384551bbde5dced3984dad":{
      "scriptId":"u66"},
    "71fe02bc78d647679ceb3cc29020d8e6":{
      "scriptId":"u67"},
    "79fde58ab13a4cebbcd23869f9f52f3e":{
      "scriptId":"u68"},
    "777fc10418e643b3b76d2afae697b455":{
      "scriptId":"u69"},
    "dd5e9c661d0c40019e99c8f0097d27c0":{
      "scriptId":"u70"},
    "4876e9977c984673a285d1ccae7d80a9":{
      "scriptId":"u71"},
    "86e339202a2047558340c9676aeac72a":{
      "scriptId":"u72"},
    "ce7d788663b54721b38eddb4b5c4cd94":{
      "scriptId":"u73"},
    "0ac62b2869b44ba784864ee1c1fdd9d2":{
      "scriptId":"u74"},
    "d8c6348d04224970ad82f6fa5a630bed":{
      "scriptId":"u75"},
    "416a00e442744f1db4a4a90801bd4ea8":{
      "scriptId":"u76"},
    "0a0c30c582eb4abfbb3ad4dcc7f4dd4a":{
      "scriptId":"u77"},
    "95fcd1c1fdbb4da8b1259fa16fa26279":{
      "scriptId":"u78"},
    "ce6f984ec84e46b781d2a6cda792beea":{
      "scriptId":"u79"},
    "27f3f86b28524153aa21175b2200980b":{
      "scriptId":"u80"},
    "6e034d48b9264374b38057333a48d08d":{
      "scriptId":"u81"},
    "32998be260a24529ab73d268161d7ee8":{
      "scriptId":"u82"},
    "b8be1425de2b47af8d07f222055ac63c":{
      "scriptId":"u83"},
    "14267f6e8a9b4c989154735a328d77f1":{
      "scriptId":"u84"},
    "1db47e63419d46098a79c0efb4295d6a":{
      "scriptId":"u85"},
    "7bece39d515a45bea8fde4db2f7f6246":{
      "scriptId":"u86"},
    "3b76f5cf3d6c4e03b4312d8447911c73":{
      "scriptId":"u87"},
    "00b6c1a880354283ac9986880256fac4":{
      "scriptId":"u88"},
    "cfef5772b96c446b890ab9ce6e18652a":{
      "scriptId":"u89"},
    "436dde0a07014dcf94f8d507ef90c153":{
      "scriptId":"u90"},
    "a6413371ac0f4d7a96d949281d8f9ed7":{
      "scriptId":"u91"},
    "6bdf3f29980b4deda21eec0b42d89bb8":{
      "scriptId":"u92"},
    "44663ecea4774eb599e50e7078b6b30c":{
      "scriptId":"u93"},
    "71027fb027554afdb567dc36a443a4e2":{
      "scriptId":"u94"},
    "3552ad9e728b4944bfbdee0b1f8899f1":{
      "scriptId":"u95"},
    "49023262c7f446588c4faffcd5b7bb66":{
      "scriptId":"u96"},
    "a875eaf64bb64bbe981e2043174baa61":{
      "scriptId":"u97"},
    "f7d2a29af9e2435ba2b974960096b474":{
      "scriptId":"u98"}}});