$axure.loadCurrentPage({
  "url":"search2_2__.html",
  "generationDate":new Date(1500857906470.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9bd4d0a09b464108887c99cb8891934c",
    "type":"Axure:Page",
    "name":"search2_2拓片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"6",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5de22b3f075b4c0bb1658b85c70e8e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":-1,
              "y":0},
            "size":{
              "width":1300,
              "height":1348}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8d21468fbec46669d639be53d62bed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":-1,
                  "y":0},
                "size":{
                  "width":1300,
                  "height":1348}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u0.png"}},
{
          "id":"6702e617081d495d8161fe236a398b10",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":532,
              "y":18},
            "size":{
              "width":253,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1027e11e6e04f15ba74e7605523cedd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":532,
                  "y":18},
                "size":{
                  "width":253,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e7352af442944dae8b519a8dbc49b89b",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":210},
            "size":{
              "width":10,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u4_line.png"}},
{
          "id":"04aa07f754b644bba0796236330ef089",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":481,
              "y":288},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e7d5d7cab3540b0a0d26510056c285c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":481,
                  "y":288},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfeea2156b23405fa908dff115204dbb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":248},
            "size":{
              "width":744,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u7_line.png"}},
{
          "id":"1bb27fc86ff2426781e238cc8e5f2ee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":968,
              "y":226},
            "size":{
              "width":212,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c632f2cd85e64d9887537a2e6fbdbc07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":968,
                  "y":226},
                "size":{
                  "width":212,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fcf48d8866f41e79914c137c6fb55ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":709,
              "y":881},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b7b657b9863456da1822b139b5f3bc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":709,
                  "y":881},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u10.png"}},
{
          "id":"4a5fc340302c438abe0c11eedb424f5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":893},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6739419d0d7a42b0b31143a7916732c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":893},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac26bc13b98b4e738cdbf646bd7f436c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF003399},
            "location":{
              "x":0,
              "y":1228},
            "size":{
              "width":1300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b56e1f1dd60403ba028ab0b3cff3b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003399},
                "location":{
                  "x":0,
                  "y":1228},
                "size":{
                  "width":1300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u14.png"}},
{
          "id":"abd1f321de824abebecb542bd23bee5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":606,
              "y":1280},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3bf56fd7abc458a97d61d95f12201bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":1280},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75c900c2e2d84177a3df97ad43d3364d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":542,
              "y":279},
            "size":{
              "width":158,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u18_image_sketch.png"}},
{
          "id":"72d4018a6c3d42c7977f9cd0b30083d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":738,
              "y":336},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3950f8247e784d41a2d71711aafef5d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":738,
                  "y":336},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed61504a7fc742b48a3e5fb4f5ecf93a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":798,
              "y":335.5},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u21_image_sketch.png"}},
{
          "id":"a2bb91e9a1ef4f05bd2e1751850abfc7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":738,
              "y":289},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67cb2b465ab84319970dfaabe24acd65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":738,
                  "y":289},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"849ae2fa18184a25b9a652ba51406459",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":799,
              "y":279},
            "size":{
              "width":158,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u18_image_sketch.png"}},
{
          "id":"c253bc4f5255476fa8ba46eff048c2bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":481,
              "y":344},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a24be7ae647d4aeeadbe3047817f6042",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":481,
                  "y":344},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efda2dc4c3e04824adfaa3bc55a1f197",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":542,
              "y":334},
            "size":{
              "width":158,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u18_image_sketch.png"}},
{
          "id":"12ae1e68ad784cab8af35b47a251278c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":519,
              "y":460},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a480a1f3f8ca438892d8edac03892c8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":519,
                  "y":460},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 content_拓片",
                      "target":{
                        "targetType":"page",
                        "url":"content____1.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"5bce5c0774974180ae97f1ab90656868",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":519,
              "y":634},
            "size":{
              "width":207,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"732229e1290e4e94905e60c1b9ea5d69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":519,
                  "y":634},
                "size":{
                  "width":207,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u30.png"}},
{
          "id":"3b82f7d91492495683b0d906a843a212",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":657},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4da8deb215ae45b6b7923b906caa2766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":657},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30046617f90544fda46e2d0b77a771e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":734},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01ed189637014fee93bf12523973f065",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":734},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c7b8325bea149aeaf49d03fe3391f4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":683},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65d93c4edc534497bd524868661427cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":683},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a5aa51f7e564aa296007fc886bf5853",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":708},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"827103f95dac47f4be64f91d23a7c6eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":708},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d0b3ca343dc744c28e89e324f2f227ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":760},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b5799e33a0944628330534ee8ee6f89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":760},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a3acfc9ec7143d8ab9b4528e273a908",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":589,
              "y":683},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b559e5ca54fd4cd0876845ee22642040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":589,
                  "y":683},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed9930d1a2ed4d238fe57db49085de1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":589,
              "y":709},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff8decfb64542b8b716d38c0d2237ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":589,
                  "y":709},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2b28427c0584103a1121e5a73120028",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":606,
              "y":735},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ab7e18207274a04bf7bf0dbf1605d8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":606,
                  "y":735},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ca9f6d7788a455580503e57b70f0427",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":606,
              "y":761},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3c38e6d2401410781320e5c7f5e921b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":606,
                  "y":761},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7cfbf54391c4e088423beffd718290f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":750,
              "y":460},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eaec01c251624829991ffee6458b2c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":750,
                  "y":460},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"5001cb81ef424098b8280318be7f25e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":750,
              "y":634},
            "size":{
              "width":207,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"165e5bb589c14cec8366f91328454d8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":750,
                  "y":634},
                "size":{
                  "width":207,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u30.png"}},
{
          "id":"3fbaf94a5b6645229f8f9baa26abf1de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":770,
              "y":657},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72bce7c2ed414524be40dbad1a4a3e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":770,
                  "y":657},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4442030b45fd46959dd2e288f265a764",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":770,
              "y":734},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c070be8d3864f2f8e8efcdea3d890cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":770,
                  "y":734},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9ccb3997fd945fa9d3139af1fac2e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":770,
              "y":683},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e986c31bb501411296fe808cbabc5146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":770,
                  "y":683},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dacc326ccac047f994d0b7266fd1fcc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":770,
              "y":708},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"406df60c4fb646ef9816e00831a37d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":770,
                  "y":708},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82feea9bc0a2491c880b1211990f1b48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":770,
              "y":760},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7fc695732df4335a214ad136d3990db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":770,
                  "y":760},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e22543cc9074ada8d58f1bc4b05836d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":820,
              "y":683},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5508aebabb4972831d52537115050f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":820,
                  "y":683},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8426738216bc4115b2dfa32e496cfdc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":820,
              "y":709},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1872232b90b345d6a19064433cc74a0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":820,
                  "y":709},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"179c462d77a044a381004c4f422cbf00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":837,
              "y":735},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c07d6ba6b44943f3b145adfc2f6be210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":837,
                  "y":735},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"defc39fe4c9d4cd1bf947cfed9549bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":837,
              "y":761},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d68c7c3ac4d6420bb7c79e8bc34d6a2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":837,
                  "y":761},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c4b4ccac009d49c29c27880d3becde46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":983,
              "y":465},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf28d0eaa39e45f893182af67e17f202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":983,
                  "y":465},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"7d496723d3e740a781ba7fa658f7faf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":983,
              "y":639},
            "size":{
              "width":207,
              "height":151},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"875e8a2d9baa43c18d2ef1b38ae45524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":983,
                  "y":639},
                "size":{
                  "width":207,
                  "height":151},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_2__/u30.png"}},
{
          "id":"93694238e9424611bc26a3944abc65e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1003,
              "y":662},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cf11a41c2dd443c9c5ecc6156cdce5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1003,
                  "y":662},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12599d64330c4c05abcb6fbac3d7a475",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1003,
              "y":739},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2c5a07c793d42588db4398be740eb2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1003,
                  "y":739},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68318b783f1a400ba9f57d83f5d1c266",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1003,
              "y":688},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ec1f50c65114b1d8ee46f3f88d8cb9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1003,
                  "y":688},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"46ef3a8c0e90432d87f76645f93ea067",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1003,
              "y":713},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f83a2222117422db86455bee95979ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1003,
                  "y":713},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ea7e0824d48c4747af621a441068b643",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1003,
              "y":765},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d34a478a16a4d02932ca4168c6c8c4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1003,
                  "y":765},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fc1628a294a14a859e58d15a82401570",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1053,
              "y":688},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81546ed6a8b84c4ea9ee3cb651598ce1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1053,
                  "y":688},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8eea1a7f799243b4963fa0a0685a646b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1053,
              "y":714},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d45167b90ee844348983670aa0f23eca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1053,
                  "y":714},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d06f13c285354261a7fdeba1a697dc05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1070,
              "y":740},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcdfd5e73b3f4f35ba8f8dd9ff45d83b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1070,
                  "y":740},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45210fbc34a04dea99c9c62935cadf1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1070,
              "y":766},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92e353b953c04bd3b5480490fa488118",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1070,
                  "y":766},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7179043479dd4dabb52dbf0d67cefbc4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":203},
            "size":{
              "width":1131,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u94_line.png"}},
{
          "id":"400301dc700048e39946a2f5b52f6802",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1100},
            "size":{
              "width":1141,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u95_line.png"}},
{
          "id":"a012d7577ce048829a463044addd6263",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u96_line.png"}},
{
          "id":"fe287bdb4c7e45d9bcff6b62af495514",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1198,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u96_line.png"}},
{
          "id":"d71ffe3d183d40568c794333115433fc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":455,
              "y":430},
            "size":{
              "width":744,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search2_2__/u98_line.png"}},
{
          "id":"9b5566f1c0424a288ee2ad3dc7a2f30e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1053,
              "y":360},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u99_image_sketch.png"}},
{
          "id":"6447c9dcc82c4b7fb438dd7a19fdc85e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":248},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f5ca70df6ce44a089a51c7daa378c41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":248},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_1___/u73.png"}},
{
          "id":"4aa907b712934d45bae22a28ea4fa7fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":326},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c4785ffd22849208c67ee115a48fde3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":326},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2af7c87a7fc4a22a74b4236da6d375b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":148,
              "y":370},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ad20fdf8004693a8cd9fff3ee69e19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":148,
                  "y":370},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59502b931b074b849203eee0b7a427b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":148,
              "y":407},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae0079ac0974fb8ac58ae89988abcb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":148,
                  "y":407},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"952cbd4b58d04ef68221ffd1ab7f45ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":148,
              "y":444},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50707779212342bc8d2a853150c4c005",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":148,
                  "y":444},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6b66571b6b446129606a9b38e44cca6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":404},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u21_image_sketch.png"}},
{
          "id":"afb7e39a91e641469ece7dd330f5ce87",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":440},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u21_image_sketch.png"}},
{
          "id":"6ff243b9d8c445a0918e5c91c7a4d613",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":366},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
},
          "images":{
            "normal~":"images/search2_2__/u21_image_sketch.png"}},
{
          "id":"790a4b02bebf442ca888a4c32c9e599b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":378,
              "y":84},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c9c4f3728347d89780e92a2a987494",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":378,
                  "y":84},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"acc77d315cf14a7f8595161a59b1827d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":463,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06f15f36a4c940dcb8784a59b79e92bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":463,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2057a7ee71fe45e9aee933d9cbdad180",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":569,
              "y":83},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79e98928493e40bc9d21d8001e8917fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":569,
                  "y":83},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65edf72b692241c9872741a901b06ab6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":674,
              "y":84},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fba0caf7edb4c1e9e4aa68b3621e0f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":674,
                  "y":84},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a4a447f43e6241b6a24189cc8631a00b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":835,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9797a76680a94cafa2a540c8eb3a8b31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":835,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5de22b3f075b4c0bb1658b85c70e8e41":{
      "scriptId":"u0"},
    "b8d21468fbec46669d639be53d62bed3":{
      "scriptId":"u1"},
    "6702e617081d495d8161fe236a398b10":{
      "scriptId":"u2"},
    "c1027e11e6e04f15ba74e7605523cedd":{
      "scriptId":"u3"},
    "e7352af442944dae8b519a8dbc49b89b":{
      "scriptId":"u4"},
    "04aa07f754b644bba0796236330ef089":{
      "scriptId":"u5"},
    "7e7d5d7cab3540b0a0d26510056c285c":{
      "scriptId":"u6"},
    "bfeea2156b23405fa908dff115204dbb":{
      "scriptId":"u7"},
    "1bb27fc86ff2426781e238cc8e5f2ee2":{
      "scriptId":"u8"},
    "c632f2cd85e64d9887537a2e6fbdbc07":{
      "scriptId":"u9"},
    "7fcf48d8866f41e79914c137c6fb55ca":{
      "scriptId":"u10"},
    "6b7b657b9863456da1822b139b5f3bc1":{
      "scriptId":"u11"},
    "4a5fc340302c438abe0c11eedb424f5a":{
      "scriptId":"u12"},
    "6739419d0d7a42b0b31143a7916732c1":{
      "scriptId":"u13"},
    "ac26bc13b98b4e738cdbf646bd7f436c":{
      "scriptId":"u14"},
    "5b56e1f1dd60403ba028ab0b3cff3b52":{
      "scriptId":"u15"},
    "abd1f321de824abebecb542bd23bee5f":{
      "scriptId":"u16"},
    "c3bf56fd7abc458a97d61d95f12201bd":{
      "scriptId":"u17"},
    "75c900c2e2d84177a3df97ad43d3364d":{
      "scriptId":"u18"},
    "72d4018a6c3d42c7977f9cd0b30083d0":{
      "scriptId":"u19"},
    "3950f8247e784d41a2d71711aafef5d3":{
      "scriptId":"u20"},
    "ed61504a7fc742b48a3e5fb4f5ecf93a":{
      "scriptId":"u21"},
    "a2bb91e9a1ef4f05bd2e1751850abfc7":{
      "scriptId":"u22"},
    "67cb2b465ab84319970dfaabe24acd65":{
      "scriptId":"u23"},
    "849ae2fa18184a25b9a652ba51406459":{
      "scriptId":"u24"},
    "c253bc4f5255476fa8ba46eff048c2bc":{
      "scriptId":"u25"},
    "a24be7ae647d4aeeadbe3047817f6042":{
      "scriptId":"u26"},
    "efda2dc4c3e04824adfaa3bc55a1f197":{
      "scriptId":"u27"},
    "12ae1e68ad784cab8af35b47a251278c":{
      "scriptId":"u28"},
    "a480a1f3f8ca438892d8edac03892c8b":{
      "scriptId":"u29"},
    "5bce5c0774974180ae97f1ab90656868":{
      "scriptId":"u30"},
    "732229e1290e4e94905e60c1b9ea5d69":{
      "scriptId":"u31"},
    "3b82f7d91492495683b0d906a843a212":{
      "scriptId":"u32"},
    "4da8deb215ae45b6b7923b906caa2766":{
      "scriptId":"u33"},
    "30046617f90544fda46e2d0b77a771e0":{
      "scriptId":"u34"},
    "01ed189637014fee93bf12523973f065":{
      "scriptId":"u35"},
    "3c7b8325bea149aeaf49d03fe3391f4f":{
      "scriptId":"u36"},
    "65d93c4edc534497bd524868661427cf":{
      "scriptId":"u37"},
    "6a5aa51f7e564aa296007fc886bf5853":{
      "scriptId":"u38"},
    "827103f95dac47f4be64f91d23a7c6eb":{
      "scriptId":"u39"},
    "d0b3ca343dc744c28e89e324f2f227ec":{
      "scriptId":"u40"},
    "3b5799e33a0944628330534ee8ee6f89":{
      "scriptId":"u41"},
    "4a3acfc9ec7143d8ab9b4528e273a908":{
      "scriptId":"u42"},
    "b559e5ca54fd4cd0876845ee22642040":{
      "scriptId":"u43"},
    "ed9930d1a2ed4d238fe57db49085de1e":{
      "scriptId":"u44"},
    "5ff8decfb64542b8b716d38c0d2237ca":{
      "scriptId":"u45"},
    "f2b28427c0584103a1121e5a73120028":{
      "scriptId":"u46"},
    "8ab7e18207274a04bf7bf0dbf1605d8e":{
      "scriptId":"u47"},
    "7ca9f6d7788a455580503e57b70f0427":{
      "scriptId":"u48"},
    "a3c38e6d2401410781320e5c7f5e921b":{
      "scriptId":"u49"},
    "f7cfbf54391c4e088423beffd718290f":{
      "scriptId":"u50"},
    "eaec01c251624829991ffee6458b2c11":{
      "scriptId":"u51"},
    "5001cb81ef424098b8280318be7f25e0":{
      "scriptId":"u52"},
    "165e5bb589c14cec8366f91328454d8a":{
      "scriptId":"u53"},
    "3fbaf94a5b6645229f8f9baa26abf1de":{
      "scriptId":"u54"},
    "72bce7c2ed414524be40dbad1a4a3e4e":{
      "scriptId":"u55"},
    "4442030b45fd46959dd2e288f265a764":{
      "scriptId":"u56"},
    "0c070be8d3864f2f8e8efcdea3d890cf":{
      "scriptId":"u57"},
    "b9ccb3997fd945fa9d3139af1fac2e59":{
      "scriptId":"u58"},
    "e986c31bb501411296fe808cbabc5146":{
      "scriptId":"u59"},
    "dacc326ccac047f994d0b7266fd1fcc6":{
      "scriptId":"u60"},
    "406df60c4fb646ef9816e00831a37d03":{
      "scriptId":"u61"},
    "82feea9bc0a2491c880b1211990f1b48":{
      "scriptId":"u62"},
    "d7fc695732df4335a214ad136d3990db":{
      "scriptId":"u63"},
    "9e22543cc9074ada8d58f1bc4b05836d":{
      "scriptId":"u64"},
    "7e5508aebabb4972831d52537115050f":{
      "scriptId":"u65"},
    "8426738216bc4115b2dfa32e496cfdc2":{
      "scriptId":"u66"},
    "1872232b90b345d6a19064433cc74a0d":{
      "scriptId":"u67"},
    "179c462d77a044a381004c4f422cbf00":{
      "scriptId":"u68"},
    "c07d6ba6b44943f3b145adfc2f6be210":{
      "scriptId":"u69"},
    "defc39fe4c9d4cd1bf947cfed9549bec":{
      "scriptId":"u70"},
    "d68c7c3ac4d6420bb7c79e8bc34d6a2f":{
      "scriptId":"u71"},
    "c4b4ccac009d49c29c27880d3becde46":{
      "scriptId":"u72"},
    "cf28d0eaa39e45f893182af67e17f202":{
      "scriptId":"u73"},
    "7d496723d3e740a781ba7fa658f7faf9":{
      "scriptId":"u74"},
    "875e8a2d9baa43c18d2ef1b38ae45524":{
      "scriptId":"u75"},
    "93694238e9424611bc26a3944abc65e4":{
      "scriptId":"u76"},
    "8cf11a41c2dd443c9c5ecc6156cdce5d":{
      "scriptId":"u77"},
    "12599d64330c4c05abcb6fbac3d7a475":{
      "scriptId":"u78"},
    "b2c5a07c793d42588db4398be740eb2c":{
      "scriptId":"u79"},
    "68318b783f1a400ba9f57d83f5d1c266":{
      "scriptId":"u80"},
    "1ec1f50c65114b1d8ee46f3f88d8cb9e":{
      "scriptId":"u81"},
    "46ef3a8c0e90432d87f76645f93ea067":{
      "scriptId":"u82"},
    "0f83a2222117422db86455bee95979ef":{
      "scriptId":"u83"},
    "ea7e0824d48c4747af621a441068b643":{
      "scriptId":"u84"},
    "3d34a478a16a4d02932ca4168c6c8c4b":{
      "scriptId":"u85"},
    "fc1628a294a14a859e58d15a82401570":{
      "scriptId":"u86"},
    "81546ed6a8b84c4ea9ee3cb651598ce1":{
      "scriptId":"u87"},
    "8eea1a7f799243b4963fa0a0685a646b":{
      "scriptId":"u88"},
    "d45167b90ee844348983670aa0f23eca":{
      "scriptId":"u89"},
    "d06f13c285354261a7fdeba1a697dc05":{
      "scriptId":"u90"},
    "fcdfd5e73b3f4f35ba8f8dd9ff45d83b":{
      "scriptId":"u91"},
    "45210fbc34a04dea99c9c62935cadf1e":{
      "scriptId":"u92"},
    "92e353b953c04bd3b5480490fa488118":{
      "scriptId":"u93"},
    "7179043479dd4dabb52dbf0d67cefbc4":{
      "scriptId":"u94"},
    "400301dc700048e39946a2f5b52f6802":{
      "scriptId":"u95"},
    "a012d7577ce048829a463044addd6263":{
      "scriptId":"u96"},
    "fe287bdb4c7e45d9bcff6b62af495514":{
      "scriptId":"u97"},
    "d71ffe3d183d40568c794333115433fc":{
      "scriptId":"u98"},
    "9b5566f1c0424a288ee2ad3dc7a2f30e":{
      "scriptId":"u99"},
    "6447c9dcc82c4b7fb438dd7a19fdc85e":{
      "scriptId":"u100"},
    "6f5ca70df6ce44a089a51c7daa378c41":{
      "scriptId":"u101"},
    "4aa907b712934d45bae22a28ea4fa7fe":{
      "scriptId":"u102"},
    "9c4785ffd22849208c67ee115a48fde3":{
      "scriptId":"u103"},
    "c2af7c87a7fc4a22a74b4236da6d375b":{
      "scriptId":"u104"},
    "c8ad20fdf8004693a8cd9fff3ee69e19":{
      "scriptId":"u105"},
    "59502b931b074b849203eee0b7a427b9":{
      "scriptId":"u106"},
    "1ae0079ac0974fb8ac58ae89988abcb2":{
      "scriptId":"u107"},
    "952cbd4b58d04ef68221ffd1ab7f45ec":{
      "scriptId":"u108"},
    "50707779212342bc8d2a853150c4c005":{
      "scriptId":"u109"},
    "e6b66571b6b446129606a9b38e44cca6":{
      "scriptId":"u110"},
    "afb7e39a91e641469ece7dd330f5ce87":{
      "scriptId":"u111"},
    "6ff243b9d8c445a0918e5c91c7a4d613":{
      "scriptId":"u112"},
    "790a4b02bebf442ca888a4c32c9e599b":{
      "scriptId":"u113"},
    "70c9c4f3728347d89780e92a2a987494":{
      "scriptId":"u114"},
    "acc77d315cf14a7f8595161a59b1827d":{
      "scriptId":"u115"},
    "06f15f36a4c940dcb8784a59b79e92bc":{
      "scriptId":"u116"},
    "2057a7ee71fe45e9aee933d9cbdad180":{
      "scriptId":"u117"},
    "79e98928493e40bc9d21d8001e8917fd":{
      "scriptId":"u118"},
    "65edf72b692241c9872741a901b06ab6":{
      "scriptId":"u119"},
    "6fba0caf7edb4c1e9e4aa68b3621e0f3":{
      "scriptId":"u120"},
    "a4a447f43e6241b6a24189cc8631a00b":{
      "scriptId":"u121"},
    "9797a76680a94cafa2a540c8eb3a8b31":{
      "scriptId":"u122"}}});