$axure.loadCurrentPage({
  "url":"search1_3___.html",
  "generationDate":new Date(1500857904430.3),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5b05e9f6f8ca46aea5a398ab07d93cca",
    "type":"Axure:Page",
    "name":"search1_3_视频",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a391199c01c04bae8c227b4039324737",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":1300,
              "height":1348}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da587745718447ba7762734f23907a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":1300,
                  "height":1348}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u0.png"}},
{
          "id":"1c40d21b7815445a8719140a6fc78661",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":532,
              "y":18},
            "size":{
              "width":253,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8cb39e6bfd0440aba92ffa1f5b128438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":532,
                  "y":18},
                "size":{
                  "width":253,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dcce8ab6e35643cca28efe4ec3423bd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":100,
              "y":210},
            "size":{
              "width":1100,
              "height":890}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f6b3244e0de4fceac9e2a210d0ea406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":100,
                  "y":210},
                "size":{
                  "width":1100,
                  "height":890}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u4.png"}},
{
          "id":"b3da4a549ded422ca637086a6c8bd82d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":210},
            "size":{
              "width":10,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u6_line.png"}},
{
          "id":"6de6a954ef324151984534321cd5a2b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":248},
            "size":{
              "width":50,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11a0faceb6484680b36036a4f054ff5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":248},
                "size":{
                  "width":50,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u7.png"}},
{
          "id":"ae7975c2babc4865a612ffa87d7a916b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":238,
              "y":326},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"399bcf5597d044ea9a4480e6c88e9d4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":238,
                  "y":326},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c737acf554243738f9ff4957d417114",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":248},
            "size":{
              "width":744,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u20_line.png"}},
{
          "id":"e10e76464ed647ae84577cdd72f4f0ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":998,
              "y":226},
            "size":{
              "width":152,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1c47355257845b4bd02a1d6f3805647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":998,
                  "y":226},
                "size":{
                  "width":152,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f677dbce89a448e1b50a41ef5b951b99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":482,
              "y":268},
            "size":{
              "width":99,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6bd7f39bb944727982d397a54f26552",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":482,
                  "y":268},
                "size":{
                  "width":99,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1cef6e58c7f74a8fbe8552b9e33264bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":709,
              "y":881},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f00e11e881d946beabffebe3dbdeb6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":709,
                  "y":881},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u77.png"}},
{
          "id":"c9c175f0448e465aafacc1c46cddc602",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":893},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0747be884e246c3a8058ff91736ba7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":893},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfce5208a8e94239a20d23261c2b53d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF003399},
            "location":{
              "x":0,
              "y":1228},
            "size":{
              "width":1300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4693af73ec9c423d82846f0370869b52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003399},
                "location":{
                  "x":0,
                  "y":1228},
                "size":{
                  "width":1300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u119.png"}},
{
          "id":"de362b37dd604a4a9fc955c2927f541f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":606,
              "y":1280},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a86c57a8b68e4fcdb2caf333b24e7563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":1280},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2160735c144847dead0c1be503aa216a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":494,
              "y":330},
            "size":{
              "width":692,
              "height":660}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5057ba9641054e469de351976a504882",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":494,
                  "y":330},
                "size":{
                  "width":692,
                  "height":660}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u37.png"}},
{
          "id":"b1235d9d79464b5ea66051cd96101a83",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":519.5,
              "y":624},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03280abaa0b04e908d096f7cac876ad2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":519.5,
                  "y":624},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"e637b619c8d7428388328ee5f4c21fe3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":953.5,
              "y":624},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d4406170cd42e29e4d9d5d02a8b03f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":953.5,
                  "y":624},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"6f05c775fd264d159c17384e216fc538",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":736.5,
              "y":624},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62d403f4c81a4d2aad810386c0eb3323",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":736.5,
                  "y":624},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"5f7044c61e444486bd80a451367e5b03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":709,
              "y":931},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e305e51a704b73baeff696823b0fca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":709,
                  "y":931},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_1___/u77.png"}},
{
          "id":"0330612fe7834b82954946fc02c23986",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":939},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f23e046474f4ebab19f64b513c4b6da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":939},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b6fb52c02494f88a9c8529c2494cc64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":520,
              "y":798},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3e4e798126474b9b13d69d5b98b320",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":520,
                  "y":798},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"9c117a6cf2c14889ae388db8d27a3270",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":736,
              "y":798},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0feca907be0740e6a94ad9a99191bdeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":736,
                  "y":798},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"b55382209fde40aa8b35c92937a8eeea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":954,
              "y":798},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177567becf7142bc8244daf323c1fcf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":954,
                  "y":798},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"b442c7bfd0724881ba2e5e2ef5f9011d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":540,
              "y":821},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"746a95cfc155400cb45013b4ef623c05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":540,
                  "y":821},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc48563e091a44298fb593df6a8d8068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":762,
              "y":821},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85306fbb694f43cb9ab1580cb717bbc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":762,
                  "y":821},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a350cac89214c3aa01f8fdf3c771403",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":982,
              "y":821},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee84c703a1624531ba409ccb854f83be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":982,
                  "y":821},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d62985f90b54459890a5c48d11e4e40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":519,
              "y":354},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"752a414762ad4fdb9f0dd98afcab36d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":519,
                  "y":354},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 content_3D",
                      "target":{
                        "targetType":"page",
                        "url":"content_3d.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"ac83a77ee3024e7d9563c4123de84c6a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":953,
              "y":354},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5d081f42fc14cf5b131c82e78286337",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":953,
                  "y":354},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"2d5644ea630f4c6d825aac44c4eb9537",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":735,
              "y":354},
            "size":{
              "width":207,
              "height":174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9f1527fd578477cb3f5a15731707e11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":735,
                  "y":354},
                "size":{
                  "width":207,
                  "height":174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_2___/u26.png"}},
{
          "id":"13a56facf1a14aebad0b35825f129eea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":519,
              "y":528},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e6dd56f0b4e426ab082f52d107984f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":519,
                  "y":528},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"0fad89b50da94e0595b0af1d85764145",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":735,
              "y":528},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff555904ee1c45729e04638cc2f6b7a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":735,
                  "y":528},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"79c1fe577c39436e971320ab14ed215c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":953,
              "y":528},
            "size":{
              "width":207,
              "height":62},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cf2424ed7394655a769daae05fcb679",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":953,
                  "y":528},
                "size":{
                  "width":207,
                  "height":62},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search1_3___/u36.png"}},
{
          "id":"bb326d39bf4f42dea113e25bcdab4f0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":539,
              "y":551},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a313f3ca6e664895b934d108e9360467",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":539,
                  "y":551},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"292d8c687057490c856a1691fef041c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":761,
              "y":551},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76db163c187446f8b71fb7b21749eba8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":761,
                  "y":551},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"649d3629a84f4459b665f483280803d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":981,
              "y":551},
            "size":{
              "width":89,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21f930638bf64c04b698d9a16bd3c2b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":981,
                  "y":551},
                "size":{
                  "width":89,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14b2d63fd2874155a8dd870773afb306",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":494,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ababa94aeb4147a7b68737cb01cca7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":494,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"a7752e870e3f423ebbf0fe74c0d747c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":579,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6e51837c9684dd69d6662a6cfbfd897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":579,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"照片list",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"df708f9f75bc4a0298614a28d00a0442",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":664,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fd75a97db164b24a76110aea96e5b35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":664,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"87bdad0b09764e67a2688a5c8042f477",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":749,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6127e00c03c40628ace233a9fa930e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":749,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u25.png"}},
{
          "id":"247da7dac55e418f93feac2190ed5021",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":834,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"899c91d8d30a4e5381c3a8febf2cadbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":834,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_5全景",
                      "target":{
                        "targetType":"page",
                        "url":"search1_5__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"701dc6edbbbc462483105499a3ec6cb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":925,
              "y":300},
            "size":{
              "width":75,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c936a0934a34ef99d5f36a82481c4b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":925,
                  "y":300},
                "size":{
                  "width":75,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 search1_5全景",
                      "target":{
                        "targetType":"page",
                        "url":"search1_5__.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/search1_1___/u27.png"}},
{
          "id":"d10086db582248168c01e8ae84550104",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":405},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"954e7634cf45477a85306cef7529e7b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":405},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9a6d64e4f24f4b75ba7c0c438c4201bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":442},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3ae0d4d1ac5484fa5810647971fc5ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":442},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07c0e9045c424c8689ba66c93536389d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":479},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e738ba2809db4df682bad774cce4221d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":479},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9456115415634b57857a01686735fcd4",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":439},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"9624713ad1b340f4a9ab466c28aa586f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":475},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"772afadf73f74d00bfd54714d0fdc336",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":401},
            "size":{
              "width":158,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"f0645322b4dc40a6a6bdf95178dbd3b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":123,
              "y":370},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a970ef240da84665a37a4c22f525096b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":123,
                  "y":370},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d79daab5e53444d4a15d8594beaaf51d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":196,
              "y":366},
            "size":{
              "width":158,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6d0ab652a9654cc2a06e503c212a3649",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":520},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search2_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search2_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true},
{
          "id":"f2e0d0938b854c459be7b1a90b345608",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":378,
              "y":84},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75a0f998a1441f4b5f5bfea56a1498b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":378,
                  "y":84},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5717befa099041b4bae14aabe1da94d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":463,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa9afd67dae248fb97cf28a259dbcaac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":463,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b3fc4caac444fb0847ba0da9b1ad37d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":569,
              "y":83},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7bb487eb3e54483be09f338bbc514a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":569,
                  "y":83},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ce0db0f3ff4142b78dfcfc88128a67f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":674,
              "y":84},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38cb73a5cea94a0bba979e0a82fa67e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":674,
                  "y":84},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"134f3eb5cc2b470ab6a808f994aab899",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":835,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e65ae81c5814d55add2e6c2a9b5aecd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":835,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a391199c01c04bae8c227b4039324737":{
      "scriptId":"u0"},
    "7da587745718447ba7762734f23907a4":{
      "scriptId":"u1"},
    "1c40d21b7815445a8719140a6fc78661":{
      "scriptId":"u2"},
    "8cb39e6bfd0440aba92ffa1f5b128438":{
      "scriptId":"u3"},
    "dcce8ab6e35643cca28efe4ec3423bd5":{
      "scriptId":"u4"},
    "5f6b3244e0de4fceac9e2a210d0ea406":{
      "scriptId":"u5"},
    "b3da4a549ded422ca637086a6c8bd82d":{
      "scriptId":"u6"},
    "6de6a954ef324151984534321cd5a2b4":{
      "scriptId":"u7"},
    "11a0faceb6484680b36036a4f054ff5b":{
      "scriptId":"u8"},
    "ae7975c2babc4865a612ffa87d7a916b":{
      "scriptId":"u9"},
    "399bcf5597d044ea9a4480e6c88e9d4d":{
      "scriptId":"u10"},
    "4c737acf554243738f9ff4957d417114":{
      "scriptId":"u11"},
    "e10e76464ed647ae84577cdd72f4f0ed":{
      "scriptId":"u12"},
    "d1c47355257845b4bd02a1d6f3805647":{
      "scriptId":"u13"},
    "f677dbce89a448e1b50a41ef5b951b99":{
      "scriptId":"u14"},
    "c6bd7f39bb944727982d397a54f26552":{
      "scriptId":"u15"},
    "1cef6e58c7f74a8fbe8552b9e33264bb":{
      "scriptId":"u16"},
    "f00e11e881d946beabffebe3dbdeb6c1":{
      "scriptId":"u17"},
    "c9c175f0448e465aafacc1c46cddc602":{
      "scriptId":"u18"},
    "c0747be884e246c3a8058ff91736ba7a":{
      "scriptId":"u19"},
    "bfce5208a8e94239a20d23261c2b53d6":{
      "scriptId":"u20"},
    "4693af73ec9c423d82846f0370869b52":{
      "scriptId":"u21"},
    "de362b37dd604a4a9fc955c2927f541f":{
      "scriptId":"u22"},
    "a86c57a8b68e4fcdb2caf333b24e7563":{
      "scriptId":"u23"},
    "2160735c144847dead0c1be503aa216a":{
      "scriptId":"u24"},
    "5057ba9641054e469de351976a504882":{
      "scriptId":"u25"},
    "b1235d9d79464b5ea66051cd96101a83":{
      "scriptId":"u26"},
    "03280abaa0b04e908d096f7cac876ad2":{
      "scriptId":"u27"},
    "e637b619c8d7428388328ee5f4c21fe3":{
      "scriptId":"u28"},
    "00d4406170cd42e29e4d9d5d02a8b03f":{
      "scriptId":"u29"},
    "6f05c775fd264d159c17384e216fc538":{
      "scriptId":"u30"},
    "62d403f4c81a4d2aad810386c0eb3323":{
      "scriptId":"u31"},
    "5f7044c61e444486bd80a451367e5b03":{
      "scriptId":"u32"},
    "c0e305e51a704b73baeff696823b0fca":{
      "scriptId":"u33"},
    "0330612fe7834b82954946fc02c23986":{
      "scriptId":"u34"},
    "8f23e046474f4ebab19f64b513c4b6da":{
      "scriptId":"u35"},
    "9b6fb52c02494f88a9c8529c2494cc64":{
      "scriptId":"u36"},
    "6d3e4e798126474b9b13d69d5b98b320":{
      "scriptId":"u37"},
    "9c117a6cf2c14889ae388db8d27a3270":{
      "scriptId":"u38"},
    "0feca907be0740e6a94ad9a99191bdeb":{
      "scriptId":"u39"},
    "b55382209fde40aa8b35c92937a8eeea":{
      "scriptId":"u40"},
    "177567becf7142bc8244daf323c1fcf3":{
      "scriptId":"u41"},
    "b442c7bfd0724881ba2e5e2ef5f9011d":{
      "scriptId":"u42"},
    "746a95cfc155400cb45013b4ef623c05":{
      "scriptId":"u43"},
    "cc48563e091a44298fb593df6a8d8068":{
      "scriptId":"u44"},
    "85306fbb694f43cb9ab1580cb717bbc6":{
      "scriptId":"u45"},
    "9a350cac89214c3aa01f8fdf3c771403":{
      "scriptId":"u46"},
    "ee84c703a1624531ba409ccb854f83be":{
      "scriptId":"u47"},
    "5d62985f90b54459890a5c48d11e4e40":{
      "scriptId":"u48"},
    "752a414762ad4fdb9f0dd98afcab36d5":{
      "scriptId":"u49"},
    "ac83a77ee3024e7d9563c4123de84c6a":{
      "scriptId":"u50"},
    "c5d081f42fc14cf5b131c82e78286337":{
      "scriptId":"u51"},
    "2d5644ea630f4c6d825aac44c4eb9537":{
      "scriptId":"u52"},
    "c9f1527fd578477cb3f5a15731707e11":{
      "scriptId":"u53"},
    "13a56facf1a14aebad0b35825f129eea":{
      "scriptId":"u54"},
    "4e6dd56f0b4e426ab082f52d107984f1":{
      "scriptId":"u55"},
    "0fad89b50da94e0595b0af1d85764145":{
      "scriptId":"u56"},
    "ff555904ee1c45729e04638cc2f6b7a3":{
      "scriptId":"u57"},
    "79c1fe577c39436e971320ab14ed215c":{
      "scriptId":"u58"},
    "6cf2424ed7394655a769daae05fcb679":{
      "scriptId":"u59"},
    "bb326d39bf4f42dea113e25bcdab4f0c":{
      "scriptId":"u60"},
    "a313f3ca6e664895b934d108e9360467":{
      "scriptId":"u61"},
    "292d8c687057490c856a1691fef041c5":{
      "scriptId":"u62"},
    "76db163c187446f8b71fb7b21749eba8":{
      "scriptId":"u63"},
    "649d3629a84f4459b665f483280803d3":{
      "scriptId":"u64"},
    "21f930638bf64c04b698d9a16bd3c2b7":{
      "scriptId":"u65"},
    "14b2d63fd2874155a8dd870773afb306":{
      "scriptId":"u66"},
    "08ababa94aeb4147a7b68737cb01cca7":{
      "scriptId":"u67"},
    "a7752e870e3f423ebbf0fe74c0d747c2":{
      "scriptId":"u68"},
    "d6e51837c9684dd69d6662a6cfbfd897":{
      "scriptId":"u69"},
    "df708f9f75bc4a0298614a28d00a0442":{
      "scriptId":"u70"},
    "9fd75a97db164b24a76110aea96e5b35":{
      "scriptId":"u71"},
    "87bdad0b09764e67a2688a5c8042f477":{
      "scriptId":"u72"},
    "a6127e00c03c40628ace233a9fa930e9":{
      "scriptId":"u73"},
    "247da7dac55e418f93feac2190ed5021":{
      "scriptId":"u74"},
    "899c91d8d30a4e5381c3a8febf2cadbd":{
      "scriptId":"u75"},
    "701dc6edbbbc462483105499a3ec6cb3":{
      "scriptId":"u76"},
    "7c936a0934a34ef99d5f36a82481c4b5":{
      "scriptId":"u77"},
    "d10086db582248168c01e8ae84550104":{
      "scriptId":"u78"},
    "954e7634cf45477a85306cef7529e7b0":{
      "scriptId":"u79"},
    "9a6d64e4f24f4b75ba7c0c438c4201bc":{
      "scriptId":"u80"},
    "f3ae0d4d1ac5484fa5810647971fc5ab":{
      "scriptId":"u81"},
    "07c0e9045c424c8689ba66c93536389d":{
      "scriptId":"u82"},
    "e738ba2809db4df682bad774cce4221d":{
      "scriptId":"u83"},
    "9456115415634b57857a01686735fcd4":{
      "scriptId":"u84"},
    "9624713ad1b340f4a9ab466c28aa586f":{
      "scriptId":"u85"},
    "772afadf73f74d00bfd54714d0fdc336":{
      "scriptId":"u86"},
    "f0645322b4dc40a6a6bdf95178dbd3b1":{
      "scriptId":"u87"},
    "a970ef240da84665a37a4c22f525096b":{
      "scriptId":"u88"},
    "d79daab5e53444d4a15d8594beaaf51d":{
      "scriptId":"u89"},
    "6d0ab652a9654cc2a06e503c212a3649":{
      "scriptId":"u90"},
    "f2e0d0938b854c459be7b1a90b345608":{
      "scriptId":"u91"},
    "a75a0f998a1441f4b5f5bfea56a1498b":{
      "scriptId":"u92"},
    "5717befa099041b4bae14aabe1da94d8":{
      "scriptId":"u93"},
    "aa9afd67dae248fb97cf28a259dbcaac":{
      "scriptId":"u94"},
    "8b3fc4caac444fb0847ba0da9b1ad37d":{
      "scriptId":"u95"},
    "d7bb487eb3e54483be09f338bbc514a6":{
      "scriptId":"u96"},
    "ce0db0f3ff4142b78dfcfc88128a67f3":{
      "scriptId":"u97"},
    "38cb73a5cea94a0bba979e0a82fa67e0":{
      "scriptId":"u98"},
    "134f3eb5cc2b470ab6a808f994aab899":{
      "scriptId":"u99"},
    "4e65ae81c5814d55add2e6c2a9b5aecd":{
      "scriptId":"u100"}}});