$axure.loadCurrentPage({
  "url":"content_3d.html",
  "generationDate":new Date(1500857906743.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2b43b16828d426fb89c3ef910195d3e",
    "type":"Axure:Page",
    "name":"content_3D",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f13ab08c9c54172ad25bfc516ed731c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":532,
              "y":18},
            "size":{
              "width":253,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a8012e425c944cba9ddb72e5ae2bc32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":532,
                  "y":18},
                "size":{
                  "width":253,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d20bc0d01e124b4f83d9d71e3089af45",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":210},
            "size":{
              "width":10,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u6_line.png"}},
{
          "id":"011cd11f87ce48d48aa0975634afc1bc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":248},
            "size":{
              "width":744,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u20_line.png"}},
{
          "id":"1d9194c9df80422a9fc0aaf0ad5cb625",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":968,
              "y":226},
            "size":{
              "width":212,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"517c7a5bbc414d24af07d3088f144434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":968,
                  "y":226},
                "size":{
                  "width":212,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"588b0fd669c94ef58d7512b7108caf2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF003399},
            "location":{
              "x":0,
              "y":1228},
            "size":{
              "width":1300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcfc462b9f5d43edaa658f594eff2d2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003399},
                "location":{
                  "x":0,
                  "y":1228},
                "size":{
                  "width":1300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u119.png"}},
{
          "id":"d53b65b0cf7f4110b239d34dd3697c76",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":606,
              "y":1280},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"982f7fa3379b4629827550dba4b1be5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":1280},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2584ea18ae7481ebe78879f60586581",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":203},
            "size":{
              "width":1131,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u10_line.png"}},
{
          "id":"a0ca3b404cae4795a0bf022690496704",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1100},
            "size":{
              "width":1141,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u11_line.png"}},
{
          "id":"0aa3c6541a05462da447327d8e6f2081",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u12_line.png"}},
{
          "id":"dcf4757672d247d396fd7e2ab6b5fefb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1198,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u12_line.png"}},
{
          "id":"d43ed14eea4b4916af1b88141b564a75",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":248},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"293d3fcf4ca446cb94e638307db07481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":248},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_1___/u73.png"}},
{
          "id":"45e9243773a14da08199286f8da9cd8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":777,
              "y":290},
            "size":{
              "width":54,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba045981a2c049d487556f79d393204c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":777,
                  "y":290},
                "size":{
                  "width":54,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"95c4dccfaca84980a7f270400d34dbdf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":511},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e96455973234aebb5da5196e732269a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":511},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59a0b3dfd2054c6ea12af3ce3ceb3c44",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":208,
              "y":342},
            "size":{
              "width":136,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7cc61f9898c04ddab35ce2bce61df1c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":208,
                  "y":342},
                "size":{
                  "width":136,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/content___/u22.png"}},
{
          "id":"24ee7358cb0946e492fae38f6cf5dcd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":249,
              "y":511},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89bf4a3e6ec347808a9812a46f32a020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":249,
                  "y":511},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9188f0f8f5d64d3aa66bd7ceebae18b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":246,
              "y":540},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ff8499c1634ab9a6938901aeba0a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":246,
                  "y":540},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28ced47e055a43c8a0b92ca353059bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":540},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bceb001a06e040559e2b8a4e42727c9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":194,
                  "y":540},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6cd05de86e642bcaa582b2686e0fce8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":566},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5528a5b63fde4478a0e4f710a1313c00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":566},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e2e3be42cb0f4ffdbe3abc51f957d9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":259,
              "y":566},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1a3e2a36f0c4e2fa833fb4653020ed3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":259,
                  "y":566},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd072b4ec0a24902bf2a9717e941bfb2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":319},
            "size":{
              "width":710,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u52_line.png"}},
{
          "id":"f63f6f1e7ccf40b99329ac64b947cb7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":472,
              "y":355},
            "size":{
              "width":716,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c83c8598b14b4a488fdf840d7a66d574",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":472,
                  "y":355},
                "size":{
                  "width":716,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/content_3d/u33.png"}},
{
          "id":"11206ec950b74b698ec4ff399ba3a002",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"36px",
            "location":{
              "x":703,
              "y":540},
            "size":{
              "width":217,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef49aa093a64151b1db2a8710f45b2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"36px",
                "location":{
                  "x":703,
                  "y":540},
                "size":{
                  "width":217,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"918cdcb32d304c999d48362e90007592",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":378,
              "y":84},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"332d9825fbae4cc8b67d250fa12766a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":378,
                  "y":84},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e5b8b76820c4063845e89121fbbdb6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":463,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb885cfba9894a0ca2b5691bace555f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":463,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"257b4a19688b4718b508d666c0450f7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":569,
              "y":83},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab50ccb303cd40bf8535f5fbcbc1fd8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":569,
                  "y":83},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ada97031e9204b7a9775b3938d90b68f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":674,
              "y":84},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aaaf2cc2a4db4f838e87f01cb9c0943b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":674,
                  "y":84},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b22bf035985495db6ddaee3ef3fc169",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":835,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0d7441411294958a7396fddcf3c737e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":835,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2f13ab08c9c54172ad25bfc516ed731c":{
      "scriptId":"u0"},
    "5a8012e425c944cba9ddb72e5ae2bc32":{
      "scriptId":"u1"},
    "d20bc0d01e124b4f83d9d71e3089af45":{
      "scriptId":"u2"},
    "011cd11f87ce48d48aa0975634afc1bc":{
      "scriptId":"u3"},
    "1d9194c9df80422a9fc0aaf0ad5cb625":{
      "scriptId":"u4"},
    "517c7a5bbc414d24af07d3088f144434":{
      "scriptId":"u5"},
    "588b0fd669c94ef58d7512b7108caf2d":{
      "scriptId":"u6"},
    "fcfc462b9f5d43edaa658f594eff2d2e":{
      "scriptId":"u7"},
    "d53b65b0cf7f4110b239d34dd3697c76":{
      "scriptId":"u8"},
    "982f7fa3379b4629827550dba4b1be5f":{
      "scriptId":"u9"},
    "f2584ea18ae7481ebe78879f60586581":{
      "scriptId":"u10"},
    "a0ca3b404cae4795a0bf022690496704":{
      "scriptId":"u11"},
    "0aa3c6541a05462da447327d8e6f2081":{
      "scriptId":"u12"},
    "dcf4757672d247d396fd7e2ab6b5fefb":{
      "scriptId":"u13"},
    "d43ed14eea4b4916af1b88141b564a75":{
      "scriptId":"u14"},
    "293d3fcf4ca446cb94e638307db07481":{
      "scriptId":"u15"},
    "45e9243773a14da08199286f8da9cd8a":{
      "scriptId":"u16"},
    "ba045981a2c049d487556f79d393204c":{
      "scriptId":"u17"},
    "95c4dccfaca84980a7f270400d34dbdf":{
      "scriptId":"u18"},
    "1e96455973234aebb5da5196e732269a":{
      "scriptId":"u19"},
    "59a0b3dfd2054c6ea12af3ce3ceb3c44":{
      "scriptId":"u20"},
    "7cc61f9898c04ddab35ce2bce61df1c0":{
      "scriptId":"u21"},
    "24ee7358cb0946e492fae38f6cf5dcd7":{
      "scriptId":"u22"},
    "89bf4a3e6ec347808a9812a46f32a020":{
      "scriptId":"u23"},
    "9188f0f8f5d64d3aa66bd7ceebae18b4":{
      "scriptId":"u24"},
    "37ff8499c1634ab9a6938901aeba0a2d":{
      "scriptId":"u25"},
    "28ced47e055a43c8a0b92ca353059bf1":{
      "scriptId":"u26"},
    "bceb001a06e040559e2b8a4e42727c9e":{
      "scriptId":"u27"},
    "e6cd05de86e642bcaa582b2686e0fce8":{
      "scriptId":"u28"},
    "5528a5b63fde4478a0e4f710a1313c00":{
      "scriptId":"u29"},
    "e2e3be42cb0f4ffdbe3abc51f957d9ec":{
      "scriptId":"u30"},
    "d1a3e2a36f0c4e2fa833fb4653020ed3":{
      "scriptId":"u31"},
    "cd072b4ec0a24902bf2a9717e941bfb2":{
      "scriptId":"u32"},
    "f63f6f1e7ccf40b99329ac64b947cb7a":{
      "scriptId":"u33"},
    "c83c8598b14b4a488fdf840d7a66d574":{
      "scriptId":"u34"},
    "11206ec950b74b698ec4ff399ba3a002":{
      "scriptId":"u35"},
    "eef49aa093a64151b1db2a8710f45b2d":{
      "scriptId":"u36"},
    "918cdcb32d304c999d48362e90007592":{
      "scriptId":"u37"},
    "332d9825fbae4cc8b67d250fa12766a4":{
      "scriptId":"u38"},
    "9e5b8b76820c4063845e89121fbbdb6a":{
      "scriptId":"u39"},
    "eb885cfba9894a0ca2b5691bace555f9":{
      "scriptId":"u40"},
    "257b4a19688b4718b508d666c0450f7a":{
      "scriptId":"u41"},
    "ab50ccb303cd40bf8535f5fbcbc1fd8e":{
      "scriptId":"u42"},
    "ada97031e9204b7a9775b3938d90b68f":{
      "scriptId":"u43"},
    "aaaf2cc2a4db4f838e87f01cb9c0943b":{
      "scriptId":"u44"},
    "1b22bf035985495db6ddaee3ef3fc169":{
      "scriptId":"u45"},
    "f0d7441411294958a7396fddcf3c737e":{
      "scriptId":"u46"}}});