$axure.loadCurrentPage({
  "url":"content____1.html",
  "generationDate":new Date(1500857906859.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3dd10db9eb7b41279655638fea2f4532",
    "type":"Axure:Page",
    "name":"content_拓片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f6011c201cc4c3b9908a9c7fbb1fbf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "location":{
              "x":532,
              "y":18},
            "size":{
              "width":253,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef089f8ebe0a409595a3eb42ae1cb3bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "location":{
                  "x":532,
                  "y":18},
                "size":{
                  "width":253,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2d08b9377937450e8469cd40110ed1fb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":446,
              "y":210},
            "size":{
              "width":10,
              "height":890},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u6_line.png"}},
{
          "id":"79002b6045c44f4ca3fef368cbe367f1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":454,
              "y":248},
            "size":{
              "width":744,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search1_1___/u20_line.png"}},
{
          "id":"9b3288a37b754fe991081c4ba8e41283",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":968,
              "y":226},
            "size":{
              "width":212,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e1059a69d640cbb584f2cc40528eae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":968,
                  "y":226},
                "size":{
                  "width":212,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"239ad91d43c641c8a2fb255e1136d34c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF003399},
            "location":{
              "x":0,
              "y":1228},
            "size":{
              "width":1300,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8afa9a864eb435e93787f2906a094ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF003399},
                "location":{
                  "x":0,
                  "y":1228},
                "size":{
                  "width":1300,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u119.png"}},
{
          "id":"9722a8d0cc4b47338bd319248039fcbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":606,
              "y":1280},
            "size":{
              "width":57,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db81a902842e40a182aea0a3c24eb479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":606,
                  "y":1280},
                "size":{
                  "width":57,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6e9ea2afbf24fed9a9bec758ad5af40",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":203},
            "size":{
              "width":1131,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u10_line.png"}},
{
          "id":"71055ff335cb450abf470f05f6dc1782",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":1100},
            "size":{
              "width":1141,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u11_line.png"}},
{
          "id":"2b9874db0e8745bfaec646aef99ad5fb",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u12_line.png"}},
{
          "id":"faf007690bfa4f85993931c026776b48",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1198,
              "y":210},
            "size":{
              "width":10,
              "height":897},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u12_line.png"}},
{
          "id":"7fed06d9b294472399bd5e0c118e5e2d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":247,
              "y":248},
            "size":{
              "width":50,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e655e4b9e374a06af878ebd2a64ab3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":247,
                  "y":248},
                "size":{
                  "width":50,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search2_1___/u73.png"}},
{
          "id":"f9ab0790842342a3adda324dac677d3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":777,
              "y":290},
            "size":{
              "width":54,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca246e0493de46b4903bc2c56d5c8d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":777,
                  "y":290},
                "size":{
                  "width":54,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6aee0224381945c2819a91c8f521d47f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":511},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e6c155cd3a841e6bfa9c3d89d08f54d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":511},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79cb0107c9e54dd690f6c1c859595d89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":208,
              "y":342},
            "size":{
              "width":136,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d70f2eeeade64bac8d4e5af6d0573074",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":208,
                  "y":342},
                "size":{
                  "width":136,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/content___/u22.png"}},
{
          "id":"a5cc0093c5c34202a235a7005bc3c12d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":249,
              "y":511},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71d815812c57408c94a0e84c6800de2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":249,
                  "y":511},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3554ad3c31444796b884401d3a787b2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":246,
              "y":540},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75ed1cea9dc6480aa7362c3ec9fca6ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":246,
                  "y":540},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3d1236cfe76a4baba7a4bc47d38dba64",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":194,
              "y":540},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2132009800ec47f1ae73e6fb4d2f6e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":194,
                  "y":540},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af494ad337c9415c967f613c27ad7bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":566},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cd3b1f2f1da4ed1828ce3ef7f22a487",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":566},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9acd1811eee14f6b800ee559862e0f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":259,
              "y":566},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"663413a4c8f046cf9b187e9ab8dc604d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":259,
                  "y":566},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"860292844e4e4bffbe7d66d2f65ac126",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":319},
            "size":{
              "width":710,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "linePattern":"dotted"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/content___/u52_line.png"}},
{
          "id":"affb46ddf6c6447b88db372f056c3061",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":520,
              "y":360},
            "size":{
              "width":560,
              "height":500}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0cba4cddd35489590c7ecf5f84271da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":520,
                  "y":360},
                "size":{
                  "width":560,
                  "height":500}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/content____1/u33.png"}},
{
          "id":"f8628621ac3f41cc9fd73e2656962fac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":593},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb886d7b6bb4c928688d401c2dce33d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":593},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0154d84037b44e9ea35d372e4f9b0053",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":249,
              "y":592},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a246029084a43609fdcf3873e4402b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":249,
                  "y":592},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d08dcbf47294f3084b2a0645ec297d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":193,
              "y":619},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b8f819b49174549a27832814dbcb723",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":193,
                  "y":619},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e056f5ebc6f4990a4c2387e3c09b11f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":255,
              "y":618},
            "size":{
              "width":50,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d328b43d433748d898f2107ae9ec0d6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":255,
                  "y":618},
                "size":{
                  "width":50,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81e806bc32b4453882dc13fed29929e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":487,
              "y":898},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"110e1112c9d74a379af466a60a0381ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":487,
                  "y":898},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"976c97c2946b4837b9725f83c30209d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":550,
              "y":916},
            "size":{
              "width":300,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3cfc7e4989b4aaf877a12b104f13877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":550,
                  "y":916},
                "size":{
                  "width":300,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8461c727bf334129962971bb0ea3d23b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":378,
              "y":84},
            "size":{
              "width":35,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce651557b86345e4857a4babd71ea891",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":378,
                  "y":84},
                "size":{
                  "width":35,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d26dc23af16944899488fa2aeb1cd851",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":463,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26c3af569944b41ad73de4d208d87cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":463,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_1_古籍",
                      "target":{
                        "targetType":"page",
                        "url":"search1_1___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"316b3be7abed4a4fb5c31f562d3e9d80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":569,
              "y":83},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be0069b60cdb496a8ea6dbe51cf9d529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":569,
                  "y":83},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_2_照片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_2___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"672245f8e05e4a468db6bd4e5004f75c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":674,
              "y":84},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41fa90643afb42cba9a0cbad22ff7020",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":674,
                  "y":84},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_3_视频",
                      "target":{
                        "targetType":"page",
                        "url":"search1_3___.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4d64821909034414930b276cee12edf2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"17px",
            "location":{
              "x":835,
              "y":84},
            "size":{
              "width":69,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5919b4cc162546e88488621591bdd710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"17px",
                "location":{
                  "x":835,
                  "y":84},
                "size":{
                  "width":69,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 search1_4拓片",
                      "target":{
                        "targetType":"page",
                        "url":"search1_4__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "2f6011c201cc4c3b9908a9c7fbb1fbf8":{
      "scriptId":"u0"},
    "ef089f8ebe0a409595a3eb42ae1cb3bd":{
      "scriptId":"u1"},
    "2d08b9377937450e8469cd40110ed1fb":{
      "scriptId":"u2"},
    "79002b6045c44f4ca3fef368cbe367f1":{
      "scriptId":"u3"},
    "9b3288a37b754fe991081c4ba8e41283":{
      "scriptId":"u4"},
    "56e1059a69d640cbb584f2cc40528eae":{
      "scriptId":"u5"},
    "239ad91d43c641c8a2fb255e1136d34c":{
      "scriptId":"u6"},
    "e8afa9a864eb435e93787f2906a094ef":{
      "scriptId":"u7"},
    "9722a8d0cc4b47338bd319248039fcbe":{
      "scriptId":"u8"},
    "db81a902842e40a182aea0a3c24eb479":{
      "scriptId":"u9"},
    "d6e9ea2afbf24fed9a9bec758ad5af40":{
      "scriptId":"u10"},
    "71055ff335cb450abf470f05f6dc1782":{
      "scriptId":"u11"},
    "2b9874db0e8745bfaec646aef99ad5fb":{
      "scriptId":"u12"},
    "faf007690bfa4f85993931c026776b48":{
      "scriptId":"u13"},
    "7fed06d9b294472399bd5e0c118e5e2d":{
      "scriptId":"u14"},
    "1e655e4b9e374a06af878ebd2a64ab3a":{
      "scriptId":"u15"},
    "f9ab0790842342a3adda324dac677d3b":{
      "scriptId":"u16"},
    "ca246e0493de46b4903bc2c56d5c8d84":{
      "scriptId":"u17"},
    "6aee0224381945c2819a91c8f521d47f":{
      "scriptId":"u18"},
    "5e6c155cd3a841e6bfa9c3d89d08f54d":{
      "scriptId":"u19"},
    "79cb0107c9e54dd690f6c1c859595d89":{
      "scriptId":"u20"},
    "d70f2eeeade64bac8d4e5af6d0573074":{
      "scriptId":"u21"},
    "a5cc0093c5c34202a235a7005bc3c12d":{
      "scriptId":"u22"},
    "71d815812c57408c94a0e84c6800de2c":{
      "scriptId":"u23"},
    "3554ad3c31444796b884401d3a787b2b":{
      "scriptId":"u24"},
    "75ed1cea9dc6480aa7362c3ec9fca6ae":{
      "scriptId":"u25"},
    "3d1236cfe76a4baba7a4bc47d38dba64":{
      "scriptId":"u26"},
    "2132009800ec47f1ae73e6fb4d2f6e68":{
      "scriptId":"u27"},
    "af494ad337c9415c967f613c27ad7bb3":{
      "scriptId":"u28"},
    "3cd3b1f2f1da4ed1828ce3ef7f22a487":{
      "scriptId":"u29"},
    "9acd1811eee14f6b800ee559862e0f1c":{
      "scriptId":"u30"},
    "663413a4c8f046cf9b187e9ab8dc604d":{
      "scriptId":"u31"},
    "860292844e4e4bffbe7d66d2f65ac126":{
      "scriptId":"u32"},
    "affb46ddf6c6447b88db372f056c3061":{
      "scriptId":"u33"},
    "b0cba4cddd35489590c7ecf5f84271da":{
      "scriptId":"u34"},
    "f8628621ac3f41cc9fd73e2656962fac":{
      "scriptId":"u35"},
    "2bb886d7b6bb4c928688d401c2dce33d":{
      "scriptId":"u36"},
    "0154d84037b44e9ea35d372e4f9b0053":{
      "scriptId":"u37"},
    "0a246029084a43609fdcf3873e4402b4":{
      "scriptId":"u38"},
    "9d08dcbf47294f3084b2a0645ec297d4":{
      "scriptId":"u39"},
    "8b8f819b49174549a27832814dbcb723":{
      "scriptId":"u40"},
    "8e056f5ebc6f4990a4c2387e3c09b11f":{
      "scriptId":"u41"},
    "d328b43d433748d898f2107ae9ec0d6a":{
      "scriptId":"u42"},
    "f81e806bc32b4453882dc13fed29929e":{
      "scriptId":"u43"},
    "110e1112c9d74a379af466a60a0381ed":{
      "scriptId":"u44"},
    "976c97c2946b4837b9725f83c30209d1":{
      "scriptId":"u45"},
    "a3cfc7e4989b4aaf877a12b104f13877":{
      "scriptId":"u46"},
    "8461c727bf334129962971bb0ea3d23b":{
      "scriptId":"u47"},
    "ce651557b86345e4857a4babd71ea891":{
      "scriptId":"u48"},
    "d26dc23af16944899488fa2aeb1cd851":{
      "scriptId":"u49"},
    "f26c3af569944b41ad73de4d208d87cd":{
      "scriptId":"u50"},
    "316b3be7abed4a4fb5c31f562d3e9d80":{
      "scriptId":"u51"},
    "be0069b60cdb496a8ea6dbe51cf9d529":{
      "scriptId":"u52"},
    "672245f8e05e4a468db6bd4e5004f75c":{
      "scriptId":"u53"},
    "41fa90643afb42cba9a0cbad22ff7020":{
      "scriptId":"u54"},
    "4d64821909034414930b276cee12edf2":{
      "scriptId":"u55"},
    "5919b4cc162546e88488621591bdd710":{
      "scriptId":"u56"}}});